#!/bin/bash -e
# select and start game server

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

# if sec updates set, then we must be running non-interactively
# so we should set default values
if [[ -n "$SEC_UPDATES" ]]; then
    APP_GAMESERVER_REPO="${APP_GAMESERVER_REPO:-https://github.com/jesinmat/linux-gameservers.git}"
    APP_GAMESERVER_BRANCH="${APP_GAMESERVER_BRANCH:-master}"
fi
$INITHOOKS_PATH/bin/gameserver.py --gameserver-repo="$APP_GAMESERVER_REPO" --gameserver-branch="$APP_GAMESERVER_BRANCH"

mkdir -p /var/log/gameserver
/usr/local/bin/gameserver-init
