#!/bin/bash
### BEGIN INIT INFO
# Provides:          Gameserver
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: gameserver
# Description:       Run installed gameserver
### END INIT INFO


case "$1" in
  start)
    /usr/local/bin/gameserver-start
    ;;
  stop)
    /usr/local/bin/gameserver-stop
    ;;
  *)
    echo "Usage: /etc/init.d/gameserver {start|stop}"
    exit 1
    ;;
esac

exit 0
